apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bananas.fruits.com
spec:
  group: fruits.com
  names:
    kind: Banana
    listKind: BananaList
    plural: bananas
    singular: banana
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: Banana is the Schema for the bananas API
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: BananaSpec defines the desired state of Banana
              properties:
                color:
                  type: string
              required:
                - color
              type: object
            status:
              description: BananaStatus defines the actual state of a Banana as recorded by the controller
              properties:
                color:
                  type: string
              required:
                - color
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}