# The role to be assumed by the operator.
# Since in a typical case the operator manages custom resources across the whole cluster,
# this is a ClusterRole (not restricted to 1 namespace)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: banana-operator
rules:
  # Allows all actions on Banana resources
  - apiGroups:
      - fruits.com
    resources:
      - bananas
      # The "status" subresource requires an explicit permission
      - bananas/status
    verbs:
      - "*"
  # Allows to read CRDs - necessary for Operator SDK to work
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "get"
      - "list"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: banana-operator
  namespace: banana-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: banana-operator
subjects:
  - kind: ServiceAccount
    name: banana-operator
    namespace: banana-operator
roleRef:
  kind: ClusterRole
  name: banana-operator
  apiGroup: ""